### ISSUE TITLE
[BUG] Docker - Collector doesn't run automatically

### ISSUE THREAD

**Issue by tuxrinku** [AnalogJ/scrutiny#143] opened 2021-02-06 22:36 UTC
**Describe the bug**
According to the description, the collector should run automatically every day. But it doesn't for me since the dashboard isn't updated. When I manually launch the command everything is fine.

**Expected behavior**
Running the collector automatically

[collector.log](https://github.com/AnalogJ/scrutiny/files/5937799/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/5937800/web.log)

**Comment by shamoon** [comment] 2021-02-06 22:41
Might be a dupe of #121 (myself and I suspect a bunch of others in the same boat)

Ps. Hoping this project is still alive!

**Closed as completed** 2021-04-24 20:32 UTC
Labels: bug

**Comment by AnalogJ** [comment] 2021-04-24 20:46
Hi everyone. 
I recently updated both the collector and all-in-one container to use Cron, rather than jobber. 
As before, the collector is scheduled to run daily, at midnight. The images now read their `cron` config from `/etc/cron.d/scrutiny`, with a default file that looks like the following:

```
# correctly route collector logs (STDOUT & STDERR) to Cron foreground (collectable by Docker STDOUT)
# cron schedule to run daily at midnight:  '0 0 * * *'
# System environmental variables are stripped by cron, source our dump of the docker environmental variables before each command (/env.sh)
0 0 * * * root . /env.sh; /scrutiny/bin/scrutiny-collector-metrics run >/proc/1/fd/1 2>/proc/1/fd/2
```

If you would like to change the collector frequency, you can mount your own crontab compatible file, but please include the `. /env.sh;` prefix when running the collector (it's required to pass docker env vars to the process).

Sorry for the long delay fixing this issue, I had a bunch of personal/professional stuff to take care of.
