### ISSUE TITLE
[FEAT] smartctl on docker rootless

### ISSUE THREAD

**Issue by ofotache** [AnalogJ/scrutiny#482] opened 2023-05-02 11:49 UTC
How can we run Scrutiny / smartctl on docker rootless?

I've included:

  -v /run/udev:/run/udev:ro \
  --cap-add SYS_RAWIO \

**Comment by AnalogJ** [comment] 2023-07-05 15:58
dupe of #191 - may not be possible.

**Closed as completed by AnalogJ** 2023-07-05 15:58 UTC
