### ISSUE TITLE
[BUG] Passing /dev/disk/by-id doesn't work

### ISSUE THREAD

**Issue by ytzelf** [AnalogJ/scrutiny#57] opened 2020-09-29 09:14 UTC
**Describe the bug**
I first tried to pass devices through /dev/disk/by-id/xxx but it didn't work. I have a feeling that would be the preferred way to refer to disks in modern apps as the traditional /dev/sdX can be a bit finicky when you change e.g. SATA port.

**Expected behavior**
Collecting data on devices passed through /dev/disk/by-id/xxx

**Screenshots**
n.a

**Log Files**

```
romain@storage:~/docker$ docker exec scrutiny-collector /scrutiny/bin/scrutiny-collector-metrics run

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                                dev-0.2.4

time="2020-09-29T09:13:19Z" level=info msg="Verifying required tools" type=metrics
time="2020-09-29T09:13:19Z" level=info msg="Executing command: smartctl --scan -j" type=metrics
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-4.19.0-11-amd64",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "--scan",
      "-j"
    ],
    "exit_status": 0
  }
}
time="2020-09-29T09:13:19Z" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
time="2020-09-29T09:13:19Z" level=info msg="Main: Completed" type=metrics

```

**Comment by seonwoolee** [comment] 2020-09-29 19:57
I worked around this by having Docker map /dev/disk/by-id/<disk> to /dev/sd[a,b,c, etc]

**Comment by AnalogJ** [comment] 2020-09-29 20:02
So internally Scrutiny uses the WWN for uniquely identifying drives. Even if your device drive short name changes, it doesn't really matter. 

I'm like 80% sure that `/dev/by-id/` is generated from WWN values anyways.

Personally I wish I could use wild-cards when attaching devices to docker `--device /dev/sd*`. 

I'm going to close this for now. Feel free to reopen if you'd like to discuss further.

**Closed as completed by AnalogJ** 2020-09-29 20:02 UTC
Labels: bug

**Comment by giesmininkas** [comment] 2022-11-08 22:46
Hi. I'd like to reopen this.

I have an use case where ability to pass a disk device by id is basically a requirement.
I'm running scrutiny in a docker container, but I'm managing the docker instance through terraform. Docker terraform provider does not (and wouldn't be able to) allow passing devices via `/dev/sd*` and `/dev/nvme*`, and querying the concrete names of the devices (via ssh, or otherwise) is far too fragile and complicated to be a viable option. 
Passing the devices by their concrete `/dev/sd*` names is troublesome because those names changes on server reboot. This means that the container usually does not start after server reboot, and the infrastructure configuration must be changed to make it work again. 

Being able to pass devices via `/dev/disk/by-id/` would solve this issue.

Thanks!

**Comment by AnalogJ** [comment] 2022-11-09 04:17
unfortunately theres some nuance here that may be missing from my comment (and the [troubleshooting guide](https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#wwn-vs-device-name))

since Scrutiny uses WWN under the hood, it really doesn't care about `/dev/sd*` vs `/dev/disk/by-id/`. The problem is the interaction between docker and smartmontools when using `--device /dev/disk/by-id` paths. 

Basically Scrutiny offloads all device detection to smartmontools, which doesn't seem to detect devices that have been passed into the docker container using `/dev/disk/by-id` paths.

Here's a workaround that may work for you, if you require "static" device references:

```
# --device=<Host Device>:<Container Device Mapping>

docker run ....
--device=/dev/disk/by-id/wwn-0x5000xxxxx:/dev/sda
--device=/dev/disk/by-id/wwn-0x5001xxxxx:/dev/sdb
--device=/dev/disk/by-id/wwn-0x5003xxxxx:/dev/sdc
...
```

Basically you can use the device wwn/uuid host reference, and map it into the container using a static device name. 

Hope that makes sense?
