### ISSUE TITLE
[BUG] Drive marked as passing SMART when it should be failing

### ISSUE THREAD

**Issue by dudeofawesome** [AnalogJ/scrutiny#148] opened 2021-03-12 03:32 UTC
**Describe the bug**
Scrutiny shows a drive as passing SMART that should clearly not be passing.

**Expected behavior**
Scrutiny should show this drive as failing in some way on the summary screen.
I'm not proficient at reading smartctl output yet, so I'm not sure if this drive is technically failing SMART or not, but clearly it _should_ be.

**Screenshots**
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1683595/110887220-bf3fb880-829e-11eb-8501-36e97ff36078.png">
<img width="999" alt="image" src="https://user-images.githubusercontent.com/1683595/110887237-c8308a00-829e-11eb-956c-65e9d942400e.png">

**Log Files**
[scrutiny-log.txt](https://github.com/AnalogJ/scrutiny/files/6127406/scrutiny-log.txt)

**Comment by Stiralbios** [comment] 2021-04-15 22:31
Same here
![Screenshot_2021-04-16 scrutiny(1)](https://user-images.githubusercontent.com/50299626/114946245-165f1d00-9e4b-11eb-83a4-22598d109274.png)
![Screenshot_2021-04-16 scrutiny](https://user-images.githubusercontent.com/50299626/114946247-18c17700-9e4b-11eb-812a-9fa751ae7049.png)

**Comment by john-clark** [comment] 2021-04-16 20:42
Mine operates the same way, smart is passing the drive internally and this is what scrutiny uses for the display. I found this that might explain why.

FROM: https://serverfault.com/questions/613049/cause-of-current-pending-sector-and-offline-uncorrectable-increase-and-then-decr
>Current Pending Sector is just that, the number of locations the disk knows about that needs to be reallocated but haven't reallocated yet since the disk has no source for the data to be reallocated. Once you write into that location the disk will automatically reallocate the area to another place and write the new data in the new place and the current pending sector cound will decrease.
>
>This is all perfectly fine and how the disk should operate.
>
>You can use diskscan on Linux or HD Tune on Windows to scan the disk for the bad locations and also attempt to "fix" the locations by making the software write into them in order to attempt the reallocation immediately.

It probably would be more useful for scrutiny to display a warning if any attribute is out of specification. Just so we know not to trust that drive anymore. Except old age of course...

**Comment by AnalogJ** [comment] 2021-06-27 02:38
this is definitely an issue, but its a dupe of #72  

closing to consolidate discussion in one thread.

**Closed as completed by AnalogJ** 2021-06-27 02:38 UTC
Labels: bug
