### ISSUE TITLE
[FEAT] automatically filter out VMDKs

### ISSUE THREAD

**Issue by bbrendon** [AnalogJ/scrutiny#49] opened 2020-09-28 22:00 UTC
![image](https://user-images.githubusercontent.com/6364477/94490589-63bfb980-019b-11eb-9498-ad8dae0013bf.png)

**Comment by AnalogJ** [comment] 2020-09-28 22:24
yeah, there's a bit of work necessary to remove virtual disks. I'm going to close this as a dupe of #39
But thanks for opening an issue :)

**Closed as completed by AnalogJ** 2020-09-28 22:24 UTC
