### ISSUE TITLE
[BUG] Wrong display state

### ISSUE THREAD

**Issue by allmazz** [AnalogJ/scrutiny#180] opened 2021-05-29 23:26 UTC
**Describe the bug**
The main page shows that the disk is healthy, although it is not.

**Screenshots**
![image](https://user-images.githubusercontent.com/37192987/120087144-45c1a480-c0ee-11eb-9630-105b4a92f99f.png)
![image](https://user-images.githubusercontent.com/37192987/120087164-67bb2700-c0ee-11eb-8453-74e6e3c458e8.png)

**Comment by AnalogJ** [comment] 2021-06-27 02:39
this is definitely an issue, but its a dupe of #72  

closing to consolidate discussion in one thread.

**Closed as completed by AnalogJ** 2021-06-27 02:39 UTC
Labels: bug
