### ISSUE TITLE
[FEAT] Change attribute row UI to make source of value, worst, threshold & failure values clear

### ISSUE THREAD

**Issue by albahrani** [AnalogJ/scrutiny#42] opened 2020-09-25 07:10 UTC
I was cruising through the _Drive Details_ and was surprised about _Spin-Up Time_ showing **Value=177** and **Worst=172**.
I was surprised that there could be a spin-up time value higher than the worst since in my opinion for spin-up time smaller is better.

I see two possible improvements for that:

1. Have different logic sets for different SMART attributes, so you could define that for spin-up time smaller is better while for others it may differ.

1. Change the column header from the opinionated word _Worst_ to something unopinionated e.g. _Maximum_ or _Highest_.

![Screenshot_2020-09-25 scrutiny](https://user-images.githubusercontent.com/11669181/94237262-dc5e1600-ff0e-11ea-829f-a24128bdfa55.png)

By the way. Great work! Thx for all.

**Comment by AnalogJ** [comment] 2020-09-26 21:04
Hey @albahrani 
Apologies for the delay. Yeah it's definitely confusing. 

Basically there's 2 types of data returned from SMART -- raw data and normalized data
- Raw data can be a simple value or a complex data structure that only the manufacturer understands.
For some events, like "start-stop" in your screenshot, its obviously just the event occurrance count. But that's not true of all attributes & all manufacturers 
- To make attribute comparisons simpler and standardized across various manufacturers, the raw data is normalized. [Normalization **seems** to be done by setting the ideal or initial value for an attribute to 100, and sets manufacturer determined failure limit as 0.](https://en.wikipedia.org/wiki/S.M.A.R.T.#ATA_S.M.A.R.T._attributes) So in an ideal world, a brand new drive would have 100 as the normalized value for all attributes, and they get closer to 0 as the drive ages. 

Thresholds are chosen by the manufacturer, so they're usually set to 0. 

So the next part is my fault. I took the failure rate data provided by Backblaze and tried to display it in the UI side by side with the existing data. The problem is that since the resolution of the normalized data is basically chosen by the manufacturer, a large change in the raw data may have little to no impact in the normalized data. [The true failure trends are mostly found by comparing the raw data.](https://www.backblaze.com/blog-smart-stats-2014-8.html) So if Backblaze data is available, I replace the data in the row with the raw data, and populate the failure rate column. 

I agree, it's not the best solution, so I've been considering a new approach: putting a mini-table within the row with something like:

| type | normalized | raw | scrutiny |
| --- | --- | --- | --- |
| value | 100 | 200 | 200 |
| worst | 100 | | |
| thresh | 0 | | 51 |
| failure | |  | 4% |

The thresh and failure entries in the scrutiny column would be provided from Backblaze's data (and possibly data submitted by other Scrutiny users in the future). 

The raw column may look redundant, however in some cases the normalized data provides a clear failure trend, and will be used to populate the scrutiny column & failure rate. 

Honestly its pretty sparse, and I don't think it's very clear either, so I'm open to alternatives/feedback.

**Comment by AnalogJ** [comment] 2020-10-11 21:05
Implementation notes:
- Find a better library for doing colspan/rowspan/grouping
- https://swimlane.github.io/ngx-datatable/#

**Comment by AnalogJ** [comment] 2022-06-10 06:03
I'm going to close this issue as a dupe of #275 

I actually have a POC for what the new UI will look like. You can check it out here: https://github.com/AnalogJ/scrutiny/issues/275#issuecomment-1151976105

**Closed as completed by AnalogJ** 2022-06-10 06:03 UTC
