### ISSUE TITLE
[BUG] - Notifications not sending

### ISSUE THREAD

**Issue by eperdeme** [AnalogJ/scrutiny#205] opened 2021-12-01 10:33 UTC
**Describe the bug**
A smart attribute is marked as FAILED but I'm not seeing any notifications.
Test notifications work via 
```
curl -X POST http://localhost:8080/api/health/notify
```

**Expected behavior**
I'd expect a notification

**Screenshots**
![Screenshot 2021-12-01 at 10 30 10](https://user-images.githubusercontent.com/158550/144218501-c97a305f-b47e-4ae2-a317-84847c7e0c07.png)

**Log Files**

ime="2021-12-01T00:00:15Z" level=info msg="Collecting smartctl results for sdg\n" type=metrics
time="2021-12-01T00:00:15Z" level=info msg="Executing command: smartctl -x -j /dev/sdg" type=metrics
time="2021-12-01T00:01:19Z" level=error msg="smartctl returned an error code (64) while processing sdg\n" type=metrics
time="2021-12-01T00:01:19Z" level=error msg="smartctl detected a error log with errors" type=metrics
time="2021-12-01T00:01:19Z" level=info msg="Publishing smartctl results for 0x500003975be81771\n" type=metrics

kernel logs suggesting the drives also sad to backup the smart failure.

[52713.869412] sd 3:0:6:0: [sdg] tag#2512 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=3s
[52713.869439] sd 3:0:6:0: [sdg] tag#2512 Sense Key : Medium Error [current] 
[52713.869445] sd 3:0:6:0: [sdg] tag#2512 Add. Sense: Unrecovered read error
[52713.869451] sd 3:0:6:0: [sdg] tag#2512 CDB: Read(16) 88 00 00 00 00 00 00 ff 52 08 00 00 00 08 00 00
[52713.869455] blk_update_request: critical medium error, dev sdg, sector 16732680 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0

**Comment by FingerlessGlov3s** [comment] 2022-01-16 23:48
Sounds similar to my bug https://github.com/AnalogJ/scrutiny/issues/203

**Comment by joe-eklund** [comment] 2022-02-14 22:00
Does smart actually report the disk as failing? Is it marked as failed on the main dashboard? If not, it will not send a notification I think.

I asked about this here https://github.com/AnalogJ/scrutiny/issues/195, which turned out to be a duplicate of https://github.com/AnalogJ/scrutiny/issues/72.

**Closed as completed** 2022-05-09 15:45 UTC
Labels: bug

**Comment by Tampa** [comment] 2025-03-22 20:56
Hate to dig this up, but I am running into this problem for some reason using 0.8.1 
Setup mattermost notifications and the test notification passes through, but disks failing I am not getting anything. I did select not to repeat notifications, but I am getting none at all.

Is there a way to reset the notification state? So that any failed disk would trigger it to send a notification

**Comment by Tampa** [comment] 2025-04-14 03:26
Just had another disk fail, no notification at all. Even setup a script to run to send notifications and added that to the config, but nothing. The test notification works perfectly, but no actual notifications seems to be sent.

**Comment by Tampa** [comment] 2025-04-14 20:14
@AnalogJ Is there an easy way to send fake device data to the collector to simulate a disk going from healthy to failed?

**Comment by Tampa** [comment] 2025-05-24 10:49
I pulled an old server out of storage that had previously reported all good drives. Upon starting that again a drive now reports as failed, but again no notification is sent to any of the configured notification endpoints.

Checking the debug log I don't see anything attempting to send a notification either. Any keywords to search for?

@AnalogJ Please respond.

Sidenote: Why does the log not follow chronological ordering? It puts the current day at the top instead of appending to the end of file?
