### ISSUE TITLE
[BUG] mirrored drives that are showing the same WWN

### ISSUE THREAD

**Issue by cessnacruzer** [AnalogJ/scrutiny#479] opened 2023-04-21 19:04 UTC
**Describe the bug**
I have two mirrored drives that are showing the same WWN, therefore only one drive shows up in the web dashboard.  The drives in question are /dev/sdb and /dev/sdf.  I manually trigged a collector run using `scrutiny-collector-metrics run` and the shell output shows both drives displaying as the same WWN.  
![shell](https://user-images.githubusercontent.com/85807693/233709936-da41ea43-147d-43bb-894f-44f1d89c94a7.jpg)
Because they have the same WWN the web ui only shows one device and SN does not match for what is shown on the host. See below screenshots.

1. Showing only /dev/sdb and not /dev/sdf
![scrutiny dash](https://user-images.githubusercontent.com/85807693/233710551-e79e2b3f-34df-4f1a-9b32-34e3941706b3.jpg)

2. Showing the SN for /dev/sdb
![scrutiny dets](https://user-images.githubusercontent.com/85807693/233710959-0069beab-4947-44ad-b38f-811504c661b3.jpg)

3. The host showing that that SN belongs to /dev/sdf not /dev/sdb as it shows in the web ui. 
![truenas disks](https://user-images.githubusercontent.com/85807693/233711195-61b90631-3a59-41fd-b707-625d14d1fbfe.jpg)

**Expected behavior**
I'm not sure how I was able to get two drives with the same WWN, but because the are the same they are not displaying properly in the web ui. 

**Screenshots**
See screenshots above. 

**Log Files**
[collector.log](https://github.com/AnalogJ/scrutiny/files/11298581/collector.log)

If related to missing devices or SMART data, please run the `collector` in DEBUG mode, and attach the log file.
See [/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md](docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md) for other troubleshooting tips.

**Comment by AnalogJ** [comment] 2023-07-05 15:59
dupe of #435

**Closed as completed by AnalogJ** 2023-07-05 15:59 UTC
Labels: bug
