### ISSUE TITLE
[BUG] Web App Not Functioning - Database Locked

### ISSUE THREAD

**Issue by joe-eklund** [AnalogJ/scrutiny#341] opened 2022-07-24 01:30 UTC
**Describe the bug**
After the web app is running for a little while, I am getting a database locked error message in the logs and the web application is not loading. Spinning down the container and spinning it back up makes the app functional for another few day(s) until I decide to check it again and it's broken.

**Expected behavior**
The web app loads.

**Log Files**

Chrome Console:

```
main-es2015.9aa07eb67b5be2859df7.js:1 ERROR Error: Uncaught (in promise): x: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"OK","url":"https://scrutiny.domain.tld/api/summary","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://scrutiny.domain.tld/api/summary: 500 OK","error":{"success":false}}
    at T (polyfills-es2015.5483988857642b9a2626.js:1:59069)
    at T (polyfills-es2015.5483988857642b9a2626.js:1:58597)
    at polyfills-es2015.5483988857642b9a2626.js:1:59878
    at l.invokeTask (polyfills-es2015.5483988857642b9a2626.js:1:54115)
    at Object.onInvokeTask (main-es2015.9aa07eb67b5be2859df7.js:1:543551)
    at l.invokeTask (polyfills-es2015.5483988857642b9a2626.js:1:54036)
    at s.runTask (polyfills-es2015.5483988857642b9a2626.js:1:49524)
    at v (polyfills-es2015.5483988857642b9a2626.js:1:56109)
    at u.invokeTask [as invoke] (polyfills-es2015.5483988857642b9a2626.js:1:55194)
    at f (polyfills-es2015.5483988857642b9a2626.js:1:67448)

```

Scrutiny Web Logs
```
time="2022-07-24T01:18:21Z" level=info msg="<redacted> - d18585b0e63e [24/Jul/2022:01:18:21 +0000] \"GET /\" 302 27 \"https://domain.tld/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36\" (1ms)" clientIP=<redacted> hostname=d18585b0e63e latency=1 method=GET path=/ referer="https://domain.tld/" respLength=27 statusCode=302 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

time="2022-07-24T01:18:22Z" level=error msg="An error occurred while retrieving device summary Could not get device summary from DB: database is locked (5) (SQLITE_BUSY)"

time="2022-07-24T01:18:22Z" level=error msg="<redacted> - d18585b0e63e [24/Jul/2022:01:18:22 +0000] \"GET /api/summary\" 500 17 \"https://scrutiny.domain.tld/web/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36\" (1ms)" clientIP=<redacted> hostname=d18585b0e63e latency=1 method=GET path=/api/summary referer="https://scrutiny.domain.tld/web/" respLength=17 statusCode=500 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
2022/07/24 01:18:22 /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/database/scrutiny_repository_device.go:33 database is locked (5) (SQLITE_BUSY)
[0.203ms] [rows:0] SELECT * FROM `devices`
```

Any ideas? Thanks.

**Comment by AnalogJ** [comment] 2022-07-24 01:40
Hey @joe-eklund 
I'll need a bit more information before I can help you:
- what version of scrutiny are you running?
- are you deploying via docker (hub/spoke or omnibus)
- arm vs amd64 arch
- do you have anything else connected to that sqlite DB? (backups, other apps, etc)

**Comment by joe-eklund** [comment] 2022-07-24 02:01
> Hey @joe-eklund I'll need a bit more information before I can help you:
> 
> * what version of scrutiny are you running?

Web app says `master#c34ee85`. `scrutiny --version` says `scrutiny version 0.4.16`.

> * are you deploying via docker (hub/spoke or omnibus)

Using Hub Spoke deployed through Docker.

> * arm vs amd64 arch

amd64. Using the following images:

- ghcr.io/analogj/scrutiny:master-collector
- ghcr.io/analogj/scrutiny:master-web
- influxdb:2.2

> * do you have anything else connected to that sqlite DB? (backups, other apps, etc)

I do have hourly backups that are run through [duplicacy](https://duplicacy.com/). Duplicacy backs up my home folder (where the folder for Scrutiny lives) to a ZFS pool on the same host.

**Comment by AnalogJ** [comment] 2022-07-24 03:35
From what I've read, this shouldn't be happening unless there's multiple connections to the SQLite DB.
To confirm, there's no other applications reading from that SQLite DB file, correct? No other versions/containers of scrutiny running on your server?

The really weird thing is that even if there was multiple processes locking up the DB file, it should be a transient error, eventually the other app should close its connection to the app.

**Comment by AnalogJ** [comment] 2022-07-24 03:36
just some notes for myself:

- https://gitlab.com/cznic/sqlite/-/issues/74
- https://gitlab.com/cznic/sqlite/-/commit/e3be4b029c0e128faa7bfb5e06f67c8fda33db4a#bb99b1baec3b0c8f02dc4e87b04926bc377fd8db_1824_1868
- https://www.sqlite.org/pragma.html#pragma_busy_timeout

**Comment by joe-eklund** [comment] 2022-07-27 15:56
> From what I've read, this shouldn't be happening unless there's multiple connections to the SQLite DB. To confirm, there's no other applications reading from that SQLite DB file, correct? No other versions/containers of scrutiny running on your server?

Sorry took me a few days to get back to you. On vacation. :) 

The only other thing is I do have another scrutiny collector from another machine (so two total) that is reporting back to the single scrutiny web instance. But I thought that was reporting directly through the scrutiny web container, so it shouldn't really be another "connection" to the DB right?

> 
> The really weird thing is that even if there was multiple processes locking up the DB file, it should be a transient error, eventually the other app should close its connection to the app.

Yes I agree. I will note the web app has been working since I restarted it on Saturday (4 days ago), but it has become frozen twice before over the past couple weeks. I will continue monitoring it and checking the logs to see if something more useful comes up to help with reproduction.

**Comment by hapylestat** [comment] 2022-07-28 23:34
can confirm the issue, using podman - everything are latest version. At start everything works, but giving the tool to work for several hours - make it in the same DB locked state.   As i'm running containers, access to a file is guaranteed to be exclusive to only one application.

Configuration - 1 UI, 2 collectors.  What more interesting, **being unable to push metrics - collectors crashing as well.**

```
2022/07/28 23:20:51 /home/runner/work/scrutiny/scrutiny/webapp/backend/pkg/database/scrutiny_repository_device.go:33 database is locked (5) (SQLITE_BUSY)
[1.065ms] [rows:0] SELECT * FROM `devices`
time="2022-07-28T23:20:51Z" level=error msg="An error occurred while retrieving device summary Could not get device summary from DB: database is locked (5) (SQLITE_BUSY)"
```

In theory, if application accessing the database from several different threads - it is same as it is accessed in a parallel. Given that UI reader and another thread writer might work in different threads, it could cause an issue when threads meats in write/read operation. It it is indeed the case, moving from Journal to WAL might help( i.e. PRAGMA journal_mode=WAL;)

**Comment by AnalogJ** [comment] 2022-08-03 05:44
quick update for everyone. I've been able to reproduce this error locally. Its definitely caused by concurrent requests to the db. I've fixed the issue via the following commit in the beta branch - https://github.com/AnalogJ/scrutiny/commit/a1b010850382bf0a9cdb08f1752f74951b8de339

The beta branch is still a bit unstable, so please don't switch to it, but you should see the fix in v0.5.0, which should be released in the next couple of days. Thanks for all your help debugging this!

**Closed as completed** 2022-08-04 15:08 UTC
Labels: bug

**Comment by AnalogJ** [comment] 2022-08-04 15:43
`v0.5.0` has been released 🥳 
If you wouldn't mind testing it out and verifing that the `SQLITE_BUSY` error is no longer occurring, that would be appreciated!

**Comment by KF5JWC** [comment] 2022-08-05 00:51
Just tried it out a few times, no longer hitting this issue!
