### ISSUE TITLE
[FEAT] Can we have more than a single FAILED status indicator (this can be missleading)

### ISSUE THREAD

**Issue by iamwoz** [AnalogJ/scrutiny#311] opened 2022-06-23 22:11 UTC
**Is your feature request related to a problem? Please describe.**
A single status indicator (FAILED) isn't useful for drives which have historical issues (ie. cable faults) or issues are indicators of future **potential** failures

**Describe the solution you'd like**
Additional status flags that offer more nuance - ie FAILING. Possible to have an option to ignore issues caused by cable faults (usually CRC errors, command timeout)

**Additional context**
This combined with notification options per flag type would be awesome https://github.com/AnalogJ/scrutiny/issues/300

**Comment by iamwoz** [comment] 2022-06-23 22:46
Would be great if an increased variety of drive states was also reflected in colours and indicators

![image](https://user-images.githubusercontent.com/85816876/175427292-9e914be3-9dee-4aa8-8c18-6bcc8338b318.png)

**Comment by AnalogJ** [comment] 2022-07-10 15:46
Hey @iamwoz 

Yeah there's been some discussion about this previously, and I intend to differentiate scrutiny/smart a bit more in the UI (and allow users to disable scrutiny analysis completely if they want). This work is being tracked in #275 

For now, you can figure out exactly what the root cause is by going to the device details, and then clicking on the "failing" attribute rows. It'll explicitly tell you if scrutiny or smart is failing. 

I'm going to close this issue as a dupe of #275, but feel free to reopen/comment if you have any questions.

**Closed as completed by AnalogJ** 2022-07-10 15:46 UTC
