### ISSUE TITLE
[FEAT] Introduce API Tokens

### ISSUE THREAD

**Issue by stavros-k** [AnalogJ/scrutiny#312] opened 2022-06-24 14:16 UTC
**Is your feature request related to a problem? Please describe.**
I want to have remote machines post metrics on my scrutiny server. Currently anyone with my URL can do that.

**Describe the solution you'd like**
I'd like to able to have an API token, so server will only accept metrics from a client that provides the correct token.

**Additional context**
It would be nice to have multiple tokens, so you can revoke any compromised. 
But also supporting 1 token would be ok (considering there isn't any now)

**Comment by AnalogJ** [comment] 2022-06-25 18:42
Partially a dupe of #34  I'm going to copy this message as a comment over there, and close this issue.

**Closed as completed** 2022-06-25 18:42 UTC
